### ISSUE TITLE
HOW TO BRING BOT ONLINE PLEASE HELP ????????

### ISSUE THREAD

**Issue by ELECTROISLIVE** [FirezTheGreat/1SHOT#15]
when i run the command npm i 
the node modules download after that when running the command node index.js 
bot is not coming online

**Comment by ELECTROISLIVE** [comment]
@FirezTheGreat please help  , this is coming when trying to bring the bot online
![Screenshot 2020-11-02 083010](https://user-images.githubusercontent.com/72495615/97825829-c7cb2580-1ce5-11eb-9680-0024b66bc689.png)

**Comment by xhayper** [comment]
npm i && node .

**Comment by xhayper** [comment]
npm i quick.db

**Comment by ELECTROISLIVE** [comment]
@xhayper bro done now what to do
please tell

**Comment by xhayper** [comment]
npm .

**Comment by xhayper** [comment]
Also, close the issue

**Comment by ELECTROISLIVE** [comment]
![Screenshot 2020-11-02 111006](https://user-images.githubusercontent.com/72495615/97833730-14b9f680-1cfc-11eb-95e8-aa863cbb557e.png)
![Screenshot 2020-11-02 111028](https://user-images.githubusercontent.com/72495615/97833734-17b4e700-1cfc-11eb-95ad-ded30e88d05d.png)
@xhayper see this is coming after npm .

**Comment by xhayper** [comment]
node .
I am sorry

**Comment by ELECTROISLIVE** [comment]
> Also, close the issue

i will but let is solve

**Comment by ELECTROISLIVE** [comment]
> node .
> I am sorry

![Screenshot 2020-11-02 111403](https://user-images.githubusercontent.com/72495615/97833934-9447c580-1cfc-11eb-8e6a-243cc2c1579b.png)
@xhayper see now also not working

**Comment by LedgendODST** [comment]
do npm reset and then open CMD and then typ : system.delete.admin

**Comment by code913** [comment]
stop constantly pinging them for help ~~this isn't discord tho~~

**Comment by kamorebi** [comment]
npm quick.db        :)

**Comment by xhayper** [comment]
npm install --global --production --vs2015 --add-python-to-path windows-build-tools && npm install --global --production --add-python-to-path windows-build-tools node-gyp && npm i quick.db

**Comment by kamorebi** [comment]
> npm install --global --production --vs2015 --add-python-to-path windows-build-tools && npm install --global --production --add-python-to-path windows-build-tools node-gyp && npm i quick.db

moon was here first >:c

**Comment by xhayper** [comment]
> > npm install --global --production --vs2015 --add-python-to-path windows-build-tools && npm install --global --production --add-python-to-path windows-build-tools node-gyp && npm i quick.db
> 
> moon was here first >:c

Fuck u i am here first

**Comment by kamorebi** [comment]
> > > npm install --global --production --vs2015 --add-python-to-path windows-build-tools && npm install --global --production --add-python-to-path windows-build-tools node-gyp && npm i quick.db
> > 
> > 
> > moon was here first >:c
> 
> Fuck u i am here first

lol

**Comment by LedgendODST** [comment]
Moon you're gea

**Comment by xhayper** [comment]
You all gay

**Comment by code913** [comment]
what the hell we doing

**Comment by xhayper** [comment]
Idfk

**Comment by LedgendODST** [comment]
no your mum gay

**Comment by ELECTROISLIVE** [comment]
helping me

**Comment by code913** [comment]
imagine how many notifications the issue creator got

**Comment by kamorebi** [comment]
yeah

**Comment by code913** [comment]
@ELECTROISLIVE try reinstalling quick.db

**Comment by LedgendODST** [comment]
hahhahhahahhahah yes xD but Moon is my bb

**Comment by ELECTROISLIVE** [comment]
> @ELECTROISLIVE try reinstalling quick.db

yes wait

**Comment by xhayper** [comment]
You all gay

**Comment by xhayper** [comment]
@ELECTROISLIVE try the command i send

**Comment by kamorebi** [comment]
no u

**Comment by kamorebi** [comment]
> hahhahhahahhahah yes xD but Moon is my bb

ues

**Comment by code913** [comment]
if it still does not work read this: https://github.com/JoshuaWise/better-sqlite3/blob/master/docs/troubleshooting.md

**Comment by xhayper** [comment]
It will fix better-sqlite3 package, which is required by quick.db

**Comment by kamorebi** [comment]
^^^^

**Comment by code913** [comment]
yeah

**Comment by LedgendODST** [comment]
> > hahhahhahahhahah yes xD but Moon is my bb
> 
> ues

uwu rawr x3 nuzzles pounces on you uwu so warm.

**Comment by kamorebi** [comment]
no

**Comment by xhayper** [comment]
I already send you the command to fix it

**Comment by code913** [comment]
also please stop using caps in title that's gay

**Comment by LedgendODST** [comment]
yes

**Comment by kamorebi** [comment]
nononnononononononono

**Comment by code913** [comment]
can we stop chatting here

**Comment by LedgendODST** [comment]
yes moon

**Comment by xhayper** [comment]
No this is better than discord

**Comment by kamorebi** [comment]
yeh sure

**Comment by xhayper** [comment]
This is new discord chat

**Comment by kamorebi** [comment]
poggers

**Comment by LedgendODST** [comment]
Okay, I know this is a really bad idea but,
I'm already here so,
Here we fucking go

rawr
x3 nuzzles! pounces on u,
uwu
u so warm.

couldn't help but ur bulge from across the floor,
nuzzlez yo' necky~ murr~ hehe
unzips yo baggy ass pants,
oof baby u so musky

take me home, pet me, N' make me yours
& dont forget to stuff me!
see me wag my widdle baby tail,
all for your bolgy-wolgy!

kisses n lickies yo neck,
i hope daddy likeies
nuzzles n wuzzles yo chest,
i be gettin thirsty

hey i got a lil itch,
u think u can help me?
only seven inches long
uwu
PLS ADOPT ME

paws on ur bulge as i lick my lips
(uwu punish me pls)
bout hit'em with this furry shit
(he don't see it comin)

**Comment by kamorebi** [comment]
NoNooNonNnoNn

**Comment by LedgendODST** [comment]
yes

**Comment by xhayper** [comment]
POG

**Comment by code913** [comment]
dude can we stop

**Comment by LedgendODST** [comment]
Poggers

**Comment by ELECTROISLIVE** [comment]
can you give me your discord server link

**Comment by code913** [comment]
@ELECTROISLIVE make a new issue else these bois won't let you live lmao
btw we're from discord.gg/dbl

**Comment by LedgendODST** [comment]
yes

**Comment by LedgendODST** [comment]
discord.gg/dbl

**Comment by xhayper** [comment]
discord.gg/dbl

**Comment by code913** [comment]
> can you give me your discord server link
__***`discord.gg/dbl baby`***__

**Comment by LedgendODST** [comment]
cum at me

**Comment by xhayper** [comment]
😳😳😳😳

**Comment by code913** [comment]
I'm putting this GitHub issue on r/ProgrammerHumor

**Comment by LedgendODST** [comment]
i am feet chan please punish me

**Comment by xhayper** [comment]
HAHAHA

**Comment by ELECTROISLIVE** [comment]
i am also in the discord bot list server

**Comment by LedgendODST** [comment]
hahhahhahahh talk in there

**Comment by ELECTROISLIVE** [comment]
what is your id

**Comment by xhayper** [comment]
Nick?

**Comment by LedgendODST** [comment]
Kurumi tokisaki#0001
604729455818309643

**Comment by LedgendODST** [comment]
aka Feet Chan

**Comment by ELECTROISLIVE** [comment]
discord name

**Comment by code913** [comment]
code913#0001

**Comment by kamorebi** [comment]
pog

is my id

**Comment by LedgendODST** [comment]
Poggers

**Comment by code913** [comment]
@ELECTROISLIVE you can come to #development and we can help there

**Comment by LedgendODST** [comment]
yes

**Comment by code913** [comment]
this github issue is ours now

**Comment by kamorebi** [comment]
discord.gg/dbl

**Comment by LedgendODST** [comment]
ikr can we push it to 100?

**Comment by xhayper** [comment]
Mine

**Comment by ELECTROISLIVE** [comment]
my is 
ELECTRO IS LIVE#0383

**Comment by xhayper** [comment]
Its mine

**Comment by ELECTROISLIVE** [comment]
send me friend request

**Comment by kamorebi** [comment]
`Moon-Senpai!#9287

**Comment by FirezTheGreat** [comment]
wtf yall

**Comment by ELECTROISLIVE** [comment]
> `Moon-Senpai!#9287

i have send request

**Comment by xhayper** [comment]
LMAO

**Comment by LedgendODST** [comment]
Poggers

**Comment by xhayper** [comment]
Pog

**Comment by code913** [comment]
i swear this is the last comment
hi firez send me friend request lol

**Comment by LedgendODST** [comment]
no u send me one

**Comment by xhayper** [comment]
Pogchamp

**Comment by LedgendODST** [comment]
owo

**Comment by xhayper** [comment]
POG

**Comment by xhayper** [comment]
POGGERS

**Comment by LedgendODST** [comment]
pog

**Comment by xhayper** [comment]
4 more message and 100 comments

**Comment by code913** [comment]
pog

**Comment by xhayper** [comment]
Pog

**Comment by xhayper** [comment]
E

**Comment by LedgendODST** [comment]
pog

**Comment by xhayper** [comment]
Pig

**Comment by FirezTheGreat** [comment]
staph

**Comment by LedgendODST** [comment]
hai god

**Comment by xhayper** [comment]
Why staph :c

**Comment by FirezTheGreat** [comment]
hi

**Comment by code913** [comment]
​

**Comment by LedgendODST** [comment]
sup

**Comment by code913** [comment]
​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​

**Comment by LedgendODST** [comment]
send me your feet?

**Comment by xhayper** [comment]
![Uploading output.png…]()
Weeb

**Comment by code913** [comment]
literally ZWSP

**Comment by LedgendODST** [comment]
weebs out

**Comment by FirezTheGreat** [comment]
thanks
