### ISSUE TITLE
Problem with join

### ISSUE THREAD

**Issue by Zemapt** [FirezTheGreat/1SHOT#17]
I have a little problem with command join

(node:7832) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'c                                                                                                                     onnection' of undefined
    at Object.run (/root/1SHOT/commands/music/join.js:26:23)
    at module.exports (/root/1SHOT/events/guild/message.js:34:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7832) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This                                                                                                                      error originated either by throwing inside of an async function without a catch                                                                                                                      block, or by rejecting a promise which was not handled with .catch(). To termina                                                                                                                     te the node process on unhandled promise rejection, use the CLI flag `--unhandle                                                                                                                     d-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejectio                                                                                                                     ns_mode). (rejection id: 1)
(node:7832) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre                                                                                                                     cated. In the future, promise rejections that are not handled will terminate the                                                                                                                      Node.js process with a non-zero exit code.

What should i can do ?

**Comment by FirezTheGreat** [comment]
on line 26 replace it with this
`if (serverQueue) serverQueue.dispatcher.connection.end()`

**Comment by FirezTheGreat** [comment]
sorry for late reply
