### ISSUE TITLE
Music commands not working

### ISSUE THREAD

**Issue by ELECTROISLIVE** [FirezTheGreat/1SHOT#19]
When i am using the music commands they are not working

**Comment by ELECTROISLIVE** [comment]
help please

**Comment by ELECTROISLIVE** [comment]
please replay

**Comment by FirezTheGreat** [comment]
@ELECTROISLIVE tell me the error

**Comment by FirezTheGreat** [comment]
not working does not help at all, be specific

**Comment by FirezTheGreat** [comment]
what type of error do u get when trying to play music?

**Comment by ELECTROISLIVE** [comment]
no error come 
when i type the music commands it does not work

**Comment by FirezTheGreat** [comment]
cant help u then, atleast some error should come on console

**Comment by ELECTROISLIVE** [comment]
ok i send you the error

**Comment by ELECTROISLIVE** [comment]
wait

**Comment by ELECTROISLIVE** [comment]
![Uploading Screenshot 2020-12-10 121614.png…]()

**Comment by ELECTROISLIVE** [comment]
see this comes when i used the command

**Comment by ELECTROISLIVE** [comment]
@FirezTheGreat

**Comment by ELECTROISLIVE** [comment]
![Screenshot 2020-12-10 121614](https://user-images.githubusercontent.com/72495615/101738143-bbf42f80-3aeb-11eb-9d86-7e41ff0ddfe0.png)
