### ISSUE TITLE
Music command not working 

### ISSUE THREAD

**Issue by ELECTROISLIVE** [FirezTheGreat/1SHOT#20]
SEE THE ERROR DURING I USE MUSIC COMMAND
![Screenshot 2020-12-10 121614](https://user-images.githubusercontent.com/72495615/101738820-b9460a00-3aec-11eb-9405-e132f5abfc47.png)

**Comment by ELECTROISLIVE** [comment]
tell please

**Comment by ELECTROISLIVE** [comment]
@FirezTheGreat

**Comment by FirezTheGreat** [comment]
update your version of ytdl-core

**Comment by FirezTheGreat** [comment]
to version 4 and above

**Comment by FirezTheGreat** [comment]
npm i ytdl-core@4.0.0
