### ISSUE TITLE
an Error while running the bot...

### ISSUE THREAD

**Issue by IamAndrew1** [FirezTheGreat/1SHOT#23]
i dont know i am getting this same error.... all time
___________________________________________________________________________________________________________

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'dblapi.js'
Require stack:
- C:\Users\stifm\Desktop\Last try\index.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:952:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:88:18)←[39m
    at Object.<anonymous> (C:\Users\stifm\Desktop\Last try\index.js:4:13)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:928:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [ ←[32m'C:\\Users\\stifm\\Desktop\\Last try\\index.js'←[39m ]
}

**Comment by code913** [comment]
You need to install the module dblapi.js from npm. Run this command:

```bash

npm install dblapi.js
```

~~why arent you using the node sdk stinky firez~~

**Comment by IamAndrew1** [comment]
> You need to install the module dblapi.js from npm. Run this command:
> 
> ```shell
> npm install dblapi.js
> ```
> 
> ~why arent you using the node sdk stinky firez~

i did it but when i run it again it shows me the same error with the other .js file
