### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by Aryansoam** [FirezTheGreat/1SHOT#26]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! discord-bot@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the discord-bot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-03-28T08_10_29_597Z-debug.log
its showing this error and also 
how can i get the dbl api key

**Comment by FirezTheGreat** [comment]
I actually forgot what causes that error so I cant tell much about it, as for the dbl api key, the dbl website gives the key to you once your bot has been verified on their site, dont bother using it if your bot is not verified yet.
