### ISSUE TITLE
Trying to Add it to custom server Need support server

### ISSUE THREAD

**Issue by O-ffender** [FirezTheGreat/1SHOT#28]
Hey Owner,
I'm trying to get in touch with you as ive tried adding the phone system to my bot but im stuck on the command phonecall as its giving me so many error so can you please provide me your discord user or support server where i can get some help as soon as possible please.

**Comment by brblacky** [comment]
function inPhoneCall (channel) {
            return client.phone.some(call => call.origin.id === channel.id || call.recipient.id === channel.id);
        }
    }
};

`some` is not defined can you tell me how to define this

**Comment by FirezTheGreat** [comment]
> Hey Owner,
> I'm trying to get in touch with you as ive tried adding the phone system to my bot but im stuck on the command phonecall as its giving me so many error so can you please provide me your discord user or support server where i can get some help as soon as possible please.

i have stopped this project and i dont have much interest in discord bots either so i wont be creating any support server, as for the error you can send it on github
