### ISSUE TITLE
help

### ISSUE THREAD

**Issue by GamingDude1** [FirezTheGreat/1SHOT#37]
hello  how to hide token of bot bez my token sometook and nuked my server so i aksed

**Comment by Khanmanan** [comment]
> hello how to hide token of bot bez my token sometook and nuked my server so i aksed

go to index.js go to last line client.login to 
 client.login(process.env.TOKEN)
Then make a new file called .env go to env file then TOKEN=YOUR BOT TOKEN HERE

also put these in line no1 
   requiree('dotenv').config();

**Comment by Khanmanan** [comment]
Make sure to give a star
