### ISSUE TITLE
Others copying your repo! 

### ISSUE THREAD

**Issue by ThinkGeoduck** [FirezTheGreat/1SHOT#39]
Bruh it's serious now. I saw a bot with the same code a few days ago, and as mentioned by NotYourFrosty , I too saw some bots with same code. When I asked the dev who was the owner of the bot, he said that it was **FULLY** coded by him and his bot was too verified. But when I asked him a simple question about discord.js, he blocked me lol without answering. I would HIGHLY recommend you making this repo private. SO MANY are copying this code. It's getting famous day by day -_- and this is leading everyone to copy this code and publish their bots on top.gg without giving credits :(

**Comment by FirezTheGreat** [comment]
okay, give me some time, ill talk to the moderators in top.gg
