### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by RazorShard** [FirezTheGreat/1SHOT#41]
Hey so I was looking through the code and the first thing I saw in the nodejs file is how The ping thingy works even when done like this Let's say the bot's name is Hello so if you type Kick @Hello (Just an example) it still replies with the embed So if possible make it so it only works when it is The first and only thing in a message Like @Hello would work but @Hello sucks wouldn not. Also almost every clone bot of this repo got deleted from top.gg lol.

**Comment by RazorShard** [comment]
@FirezTheGreat

**Comment by FirezTheGreat** [comment]
> Also almost every clone bot of this repo got deleted from top.gg lol.
glad to hear that.

**Comment by FirezTheGreat** [comment]
you can do something like this

`if (message.content.toLowerCase() === `<@${bot.user.id}>`) return message.channel.send(`Bot's prefix is ${PREFIX}`)`

this ensures that there is no content other than the bot ping itself
