### ISSUE TITLE
Hey buddy

### ISSUE THREAD

**Issue by gamerspodcast** [FirezTheGreat/1SHOT#42]
Hi, i don't know how to contact you. Your project is awesome , but the thing is i don't want some features like nsfw,music.So, when i deleted the nsfw file/folder i won't run..How to solve this issue..Reply asap tq

**Comment by FirezTheGreat** [comment]
[go to line 12](https://github.com/FirezTheGreat/1SHOT/blob/main/handler/command.js) and remove the folder names u dont want from the array
