### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by killerbossoriginal** [FirezTheGreat/1SHOT#43]
How can i add a command to help?

**Comment by FirezTheGreat** [comment]
create a file in any existing folder and make the config and done (copy config from any file and change the name of that config)

**Comment by killerbossoriginal** [comment]
I tried, created test.js and put this code inside but it doesn't work, how do I do it?


const { MessageEmbed } = require('discord.js');
module.exports = {
    config: {
        name: "test",
        aliases: [],
        category: "Owner",
        description: "Test if bot run",
        usage: "",
        accessableby: "owner"
    },
    run: async (bot, message, args) => {
     let owner = '845768796841050112'

        if (!owner.includes(message.author.id))return;
   		const embed = new MessageEmbed()
			.setTitle('I am working!')
			.setColor('GREEN')
			.setImage('https://media.giphy.com/media/gw3IWyGkC0rsazTi/200.gif');
		message.channel.send(embed);
    }
}
