### ISSUE TITLE
I tried to add a command to the help but it doesn't work

### ISSUE THREAD

**Issue by killerbossoriginal** [FirezTheGreat/1SHOT#45]
I tried, created test.js and put this code inside but does not appear in the help, how do I do it?

const { MessageEmbed } = require('discord.js');

module.exports = {
    config: {
        name: "test",
        aliases: [],
        category: "Owner",
        description: "Test if bot run",
        usage: "",
        accessableby: "owner"
    },
    run: async (bot, message, args) => {
     let owner = '845768796841050112'

        if (!owner.includes(message.author.id))return;
   		const embed = new MessageEmbed()
			.setTitle('I am working!')
			.setColor('GREEN')
			.setImage('https://media.giphy.com/media/gw3IWyGkC0rsazTi/200.gif');
		message.channel.send(embed);
    }
}

**Comment by FirezTheGreat** [comment]
do you receive any errors? also in which folder is the `test.js` file in?

**Comment by FirezTheGreat** [comment]
if its a new folder then you have to add the `folder name` to the array in [line 12](https://github.com/FirezTheGreat/1SHOT/blob/main/handler/command.js)

**Comment by FirezTheGreat** [comment]
also change `aliases: ['']` to `noalias: ['']`
